// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "hardhat/types/artifacts";

import { CashierDeposit$Type } from "./CashierDeposit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CashierDeposit"]: CashierDeposit$Type;
    ["contracts/CashierDeposit.sol:CashierDeposit"]: CashierDeposit$Type;
  }

  interface ContractTypesMap {
    ["CashierDeposit"]: GetContractReturnType<CashierDeposit$Type["abi"]>;
    ["contracts/CashierDeposit.sol:CashierDeposit"]: GetContractReturnType<CashierDeposit$Type["abi"]>;
  }
}
