export const quests = [
  {
    challengeName: 'Play the Field',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    currentXP: 20000,
    totalXP: 50000,
    challengeCompleted: false,
  },
  {
    challengeName: 'Double Down',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    currentXP: 40000,
    totalXP: 50000,
    challengeCompleted: false,
  },
  {
    challengeName: 'Underdog Backer',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    challengeCompleted: true,
  },
  {
    challengeName: 'Mastery',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    currentXP: 10000,
    totalXP: 50000,
    challengeCompleted: false,
  },
  {
    challengeName: 'High Roller',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    challengeCompleted: true,
  },
  {
    challengeName: 'Xp Hunter',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    currentXP: 10000,
    totalXP: 50000,
    challengeCompleted: false,
  },
  {
    challengeName: 'Hot Streak',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    currentXP: 10000,
    totalXP: 50000,
    challengeCompleted: false,
  },
  {
    challengeName: 'Super Streak',
    challengeCredit: '1250',
    variant: 'small' as 'small' | 'large',
    challengeCompleted: true,
  },
] as const;
