// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "hardhat/types/artifacts";

import { ECDSA$Type } from "./ECDSA";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ECDSA"]: ECDSA$Type;
    ["@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA"]: ECDSA$Type;
  }

  interface ContractTypesMap {
    ["ECDSA"]: GetContractReturnType<ECDSA$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/ECDSA.sol:ECDSA"]: GetContractReturnType<ECDSA$Type["abi"]>;
  }
}
