[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_cashier = "CizWDMr17EATDas9gerTNCT7Z1t95zRxVtPDDmTtFEvb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/solana_cashier",
]
