// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "hardhat/types/artifacts";

import { TestToken$Type } from "./TestToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestToken"]: TestToken$Type;
    ["contracts/TestToken.sol:TestToken"]: TestToken$Type;
  }

  interface ContractTypesMap {
    ["TestToken"]: GetContractReturnType<TestToken$Type["abi"]>;
    ["contracts/TestToken.sol:TestToken"]: GetContractReturnType<TestToken$Type["abi"]>;
  }
}
