// This file is autogenerated by deploy.js. Do not edit manually.
import { abi as sepoliaCashierDepositAbi } from "./ignition/deployments/chain-11155111/artifacts/CashierDeposit#CashierDeposit.json";
import sepoliaDeployments from "./ignition/deployments/chain-11155111/deployed_addresses.json";
import sepoliaParameters from "./ignition/parameters/sepolia.json";
import { abi as polygonCashierDepositAbi } from "./ignition/deployments/chain-137/artifacts/CashierDeposit#CashierDeposit.json";
import polygonDeployments from "./ignition/deployments/chain-137/deployed_addresses.json";
import polygonParameters from "./ignition/parameters/polygon.json";
import { abi as polygonAmoyCashierDepositAbi } from "./ignition/deployments/chain-80002/artifacts/CashierDeposit#CashierDeposit.json";
import polygonAmoyDeployments from "./ignition/deployments/chain-80002/deployed_addresses.json";
import polygonAmoyParameters from "./ignition/parameters/polygonAmoy.json";

export default {
  CashierDeposit: {
    1: {
      abi: sepoliaCashierDepositAbi,
      address: "0x52FbEd51F99549F3C55CD2611C30A7Df29d259cd" as `0x${string}`,
      parameters: { allowedTokenAddress: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" },
    },
    11155111: {
      abi: sepoliaCashierDepositAbi,
      address: sepoliaDeployments["CashierDeposit#CashierDeposit"] as `0x${string}`,
      parameters: sepoliaParameters["CashierDeposit"],
    },
    137: {
      abi: polygonCashierDepositAbi,
      address: polygonDeployments["CashierDeposit#CashierDeposit"] as `0x${string}`,
      parameters: polygonParameters["CashierDeposit"],
    },
    80002: {
      abi: polygonAmoyCashierDepositAbi,
      address: polygonAmoyDeployments["CashierDeposit#CashierDeposit"] as `0x${string}`,
      parameters: polygonAmoyParameters["CashierDeposit"],
    },
  },
} as const;
