// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "hardhat/types/artifacts";

import { CashierWithdraw$Type } from "./CashierWithdraw";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CashierWithdraw"]: CashierWithdraw$Type;
    ["contracts/CashierWithdraw.sol:CashierWithdraw"]: CashierWithdraw$Type;
  }

  interface ContractTypesMap {
    ["CashierWithdraw"]: GetContractReturnType<CashierWithdraw$Type["abi"]>;
    ["contracts/CashierWithdraw.sol:CashierWithdraw"]: GetContractReturnType<CashierWithdraw$Type["abi"]>;
  }
}
