name: Run pull request checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      #      - name: Install pnpm
      #        run: |
      #          npm install -g pnpm
      #          SHELL=bash pnpm setup
      #          echo "PNPM_HOME=/usr/local/bin" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.2

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Authenticate with npmjs
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install NestJS CLI
        run: pnpm install -g @nestjs/cli

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          cp apps/admin/.env.example apps/admin/.env
          cp apps/ui/.env.example apps/ui/.env
          pnpm build
